name: lpy-doc
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  - openalea.lpy
  - oawidgets
  - pip
  - pip:
    - pydata-sphinx-theme
    - myst-parser
    - sphinx-favicon
    - nbsphinx
    - pandoc
    - ipykernel
    - sphinx-copybutton
    - ipython_genutils
